#!/usr/bin/env ruby

# Read from e.g. 2.input if no arg given, otherwise read example input from end of file.

input = ARGV.empty? ? DATA.readlines(chomp: true) : File.new(__FILE__ + '.input').readlines(chomp: true)

score = 0

puts "#1:"
puts score

score = 0

puts "#2:"
puts score

__END__
