#!/usr/bin/env ruby

# Read from e.g. 2.input if no arg given, otherwise read example input from end of file.

input = ARGV.empty? ? DATA.readlines : File.new(__FILE__ + '.input').readlines

counts = input.map do |line|
  reds_in_line = line.split(?;).map { _1.scan(/\d+ red/) }.flatten
  reds = reds_in_line.map {_1[/\d+/].to_i}.max

  greens_in_line = line.split(?;).map { _1.scan(/\d+ green/) }.flatten
  greens = greens_in_line.map {_1[/\d+/].to_i}.max

  blues_in_line = line.split(?;).map { _1.scan(/\d+ blue/) }.flatten
  blues = blues_in_line.map {_1[/\d+/].to_i}.max
  {
    reds:,
    greens:,
    blues:
  }
end

score = 0
counts.each_with_index do |r,idx|
  if r[:reds] <= 12 && r[:greens] <= 13 && r[:blues] <= 14
    score += (idx +1)
  end
end

puts "#1:"
puts score

score = 0
counts.each_with_index do |r,idx|
  score += (r[:reds] * r[:greens] * r[:blues])
end

puts "#2:"
puts score

__END__
Game 1: 3 blue, 4 red; 1 red, 2 green, 6 blue; 2 green
Game 2: 1 blue, 2 green; 3 green, 4 blue, 1 red; 1 green, 1 blue
Game 3: 8 green, 6 blue, 20 red; 5 blue, 4 red, 13 green; 5 green, 1 red
Game 4: 1 green, 3 red, 6 blue; 3 green, 6 red; 3 green, 15 blue, 14 red
Game 5: 6 red, 1 blue, 3 green; 2 blue, 1 red, 2 green
