#!/usr/bin/env ruby

# https://adventofcode.com/2023/day/4
# Read from e.g. 2.input if no arg given, otherwise read example input from end of file.
input = ARGV.empty? ? DATA.readlines(chomp: true) : File.new(__FILE__ + '.input').readlines(chomp: true)

cards = input.map{_1.split('|')}
cards.map! do |(winnum,havenum)|
  [winnum[/:.*/],havenum]
end

score = 0

cards.each_with_index do |(winnums,havenums), idx|
  matches = (winnums.scan(/\d+/) & havenums.scan(/\d+/))
  if matches.count != 0
    score += 2 ** (matches.count - 1)
  end
end

puts "#1:"
puts score

score = 0

card_matches = []
cards.each_with_index do |(winnums,havenums), idx|
  matches = (winnums.scan(/\d+/) & havenums.scan(/\d+/))
  card_matches[idx] = matches.count
end
card_matches.reverse!

card_scores = {}

cards.reverse.each_with_index do |card,idx|
  this_score = 1
  (card_matches[idx]).times do |step|
    this_score += card_scores[idx - step - 1]
  end
  card_scores[idx] = this_score
  score += this_score
end

puts "#2:"
puts score

__END__
Card 1: 41 48 83 86 17 | 83 86  6 31 17  9 48 53
Card 2: 13 32 20 16 61 | 61 30 68 82 17 32 24 19
Card 3:  1 21 53 59 44 | 69 82 63 72 16 21 14  1
Card 4: 41 92 73 84 69 | 59 84 76 51 58  5 54 83
Card 5: 87 83 26 28 32 | 88 30 70 12 93 22 82 36
Card 6: 31 18 13 56 72 | 74 77 10 23 35 67 36 11
