#!/usr/bin/env ruby

# Puzzle PUZZLENUM: https://adventofcode.com/2021/day/DAYNUM#partPARTNUM
# Felix Wolfsteller

$DEBUG = (ARGV.delete '-d') ? true : false

def dputs string ; STDERR.puts string if $DEBUG ; end

dputs "enabled debugging output"

lines = ARGF.readlines

exit 0
